### PR TITLE
Feature/solution

### PR DESCRIPTION
**Pull request by tanmoy-sen-tech**
movie(desktop)
movies(desktop)

### CODE REVIEW

**Comment by tanmoy-sen-tech** [comment]
**FIX**

- Fixed movies and movie component with subscribe
- Fixed image names issue
- added proper data  type for all properties
- Resolve CSS and layout bug
- resolve compile and run time bugs
- resolved rxjs issue
- fixed jest test and lint errors

**Refactors**

- created Movies feature module
- created movies module as lazy loaded to improve bundle size
- handled memory leaks of subscription
- used async pipes for auto unsubscribe
- created void subject to destroy manual subscription on component destroy
- avoided extra api call for fetching specific movie details
- used container/presenter pattern and created movie-details component
- updated component folder structure
- used variables for CSS colors 
- segregated interfaces
- created separated testing stub file for UTC mock data

**Improvements**
 
- created standalone loading spinner component
- updated component to include loader-spinner till data is not present 
- converted jpeg images to webp for better performance
- created method to convert jpeg filenames to webp filenames
- Added dynamic alt attribute for images
- Added trackBy for *ngFor
- added font swap property to resolve font flickering and improve performance
- added pre-connect for API response URL(index.html) to reduce load time
- added meta description to improve SEO and better google web vitals score
- changed CTA details/IMDB button color to improve accessibility web vital score  
- updated package.json for UTC coverage generation

**Comment by tanmoy-sen-tech** [comment]
@andrantis @smcmurrin please review. Let me know if there is anything you want to discuss.

**Comment by tanmoy-sen-tech** [comment]
@smcmurrin @andrantis good morning..can you let me know if I need to raise PR to degreed repo or this PR in forked repo is fine for review?

**Comment by andrantis** [comment]
@tanmoy-sen-tech Hi Tanmoy. You are good with this submission. The recruiter will let you know of the next steps.

**Pull request closed without merging**
